## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os: 
  - linux
  - osx
  - windows

arch:
  - x64
  - x86
  - arm64

julia:
  - 1
  - nightly

matrix: 
  allow_failures:
    - arch: arm64
  exclude:
    - os: osx
      arch: x86
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; 
              cd(Pkg.dir("LinRegSubsetSelection")); 
              Pkg.add("Coverage"); 
              include("process_src_coverage.jl")
              Coveralls.submit(process_folder2()); 
              Codecov.submit(process_folder2())'